// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://syibrvgzqxokhrvylzgp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN5aWJydmd6cXhva2hydnlsemdwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NTQxMTQsImV4cCI6MjA3MDAzMDExNH0.HZXuqNxBI_oA-FGs-3OVylS9WoLtER251pvgfdQXdO4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});